name = "enginemarket-api"
main = "src/worker/index.ts"
compatibility_date = "2024-01-01"

# D1 Database Binding
[[d1_databases]]
binding = "enginemarket"
database_name = "enginemarket"
database_id = "20a319ad-0f43-4b68-8a14-1a631321153d"

# Production Environment
[env.production]
name = "enginemarket-api-prod"

[[env.production.d1_databases]]
binding = "enginemarket"
database_name = "enginemarket"
database_id = "20a319ad-0f43-4b68-8a14-1a631321153d"

# Development Environment
[env.development]
name = "enginemarket-api-dev"

[[env.development.d1_databases]]
binding = "enginemarket"
database_name = "enginemarket"
database_id = "20a319ad-0f43-4b68-8a14-1a631321153d"




